volumes:
  postgresql:

services:
  db_postg:
    image: postgres
    restart: always
    volumes:
      - ./docker-entrypoint.sql:/docker-entrypoint-initdb.d/docker-entrypoint.sql
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "hibernatedb"
      POSTGRES_USER: "hibernateuser"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"